# Generated by Django 4.2 on 2024-04-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'фидбэк', 'verbose_name_plural': 'фидбэки'},
        ),
    ]
