# Generated by Django 4.2 on 2024-04-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='имя автора')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, verbose_name='название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='books.category', verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='название книги')),
                ('isbn', models.CharField(verbose_name='ISBN')),
                ('pageCount', models.SmallIntegerField(blank=True, null=True, verbose_name='кол-во страниц')),
                ('publishedDate', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('thumbnailUrl', models.URLField(blank=True, null=True, verbose_name='ссылка на картинку')),
                ('thumbnail', models.ImageField(upload_to='books_images/', verbose_name='картинка')),
                ('shortDescription', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('longDescription', models.TextField(blank=True, null=True, verbose_name='подробное описание')),
                ('status', models.CharField(verbose_name='статус')),
                ('authors', models.ManyToManyField(related_name='books', to='books.author', verbose_name='авторы')),
                ('categories', models.ManyToManyField(related_name='books', to='books.category', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
